// Code generated by Kitex v0.11.3. DO NOT EDIT.

package productcatalogservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	product "github.com/zjhM3l/go-e-commerce/kitex_gen/product"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListProducts": kitex.NewMethodInfo(
		listProductsHandler,
		newProductCatalogServiceListProductsArgs,
		newProductCatalogServiceListProductsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetProduct": kitex.NewMethodInfo(
		getProductHandler,
		newProductCatalogServiceGetProductArgs,
		newProductCatalogServiceGetProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SearchProducts": kitex.NewMethodInfo(
		searchProductsHandler,
		newProductCatalogServiceSearchProductsArgs,
		newProductCatalogServiceSearchProductsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	productCatalogServiceServiceInfo                = NewServiceInfo()
	productCatalogServiceServiceInfoForClient       = NewServiceInfoForClient()
	productCatalogServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return productCatalogServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return productCatalogServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return productCatalogServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ProductCatalogService"
	handlerType := (*product.ProductCatalogService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "product",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.11.3",
		Extra:           extra,
	}
	return svcInfo
}

func listProductsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*product.ProductCatalogServiceListProductsArgs)
	realResult := result.(*product.ProductCatalogServiceListProductsResult)
	success, err := handler.(product.ProductCatalogService).ListProducts(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductCatalogServiceListProductsArgs() interface{} {
	return product.NewProductCatalogServiceListProductsArgs()
}

func newProductCatalogServiceListProductsResult() interface{} {
	return product.NewProductCatalogServiceListProductsResult()
}

func getProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*product.ProductCatalogServiceGetProductArgs)
	realResult := result.(*product.ProductCatalogServiceGetProductResult)
	success, err := handler.(product.ProductCatalogService).GetProduct(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductCatalogServiceGetProductArgs() interface{} {
	return product.NewProductCatalogServiceGetProductArgs()
}

func newProductCatalogServiceGetProductResult() interface{} {
	return product.NewProductCatalogServiceGetProductResult()
}

func searchProductsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*product.ProductCatalogServiceSearchProductsArgs)
	realResult := result.(*product.ProductCatalogServiceSearchProductsResult)
	success, err := handler.(product.ProductCatalogService).SearchProducts(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductCatalogServiceSearchProductsArgs() interface{} {
	return product.NewProductCatalogServiceSearchProductsArgs()
}

func newProductCatalogServiceSearchProductsResult() interface{} {
	return product.NewProductCatalogServiceSearchProductsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListProducts(ctx context.Context, request *product.ListProductsReq) (r *product.ListProductsResp, err error) {
	var _args product.ProductCatalogServiceListProductsArgs
	_args.Request = request
	var _result product.ProductCatalogServiceListProductsResult
	if err = p.c.Call(ctx, "ListProducts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetProduct(ctx context.Context, request *product.GetProductReq) (r *product.GetProductResp, err error) {
	var _args product.ProductCatalogServiceGetProductArgs
	_args.Request = request
	var _result product.ProductCatalogServiceGetProductResult
	if err = p.c.Call(ctx, "GetProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchProducts(ctx context.Context, request *product.SearchProductsReq) (r *product.SearchProductsResp, err error) {
	var _args product.ProductCatalogServiceSearchProductsArgs
	_args.Request = request
	var _result product.ProductCatalogServiceSearchProductsResult
	if err = p.c.Call(ctx, "SearchProducts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
