// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	auth "github.com/zjhM3l/go-e-commerce/biz/router/auth"
	cart "github.com/zjhM3l/go-e-commerce/biz/router/cart"
	checkout "github.com/zjhM3l/go-e-commerce/biz/router/checkout"
	order "github.com/zjhM3l/go-e-commerce/biz/router/order"
	payment "github.com/zjhM3l/go-e-commerce/biz/router/payment"
	product "github.com/zjhM3l/go-e-commerce/biz/router/product"
	user "github.com/zjhM3l/go-e-commerce/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	user.Register(r)

	product.Register(r)

	checkout.Register(r)

	payment.Register(r)

	order.Register(r)

	cart.Register(r)

	auth.Register(r)
}
